import CloseIcon from '../../../assets/icons/close-icon.svg';

export {CloseIcon};

export const icon = {
  calendar: 'calendar',
  search: 'search',
  flag: 'flag',
  add: 'add',
  add_circle: 'add-circle',
  list_outline: 'list-outline',
  today: 'today',
  albums: 'albums',
  ellipsis_horizontal: 'ellipsis-horizontal',
  ellipsis_horizontal_circle: 'ellipsis-horizontal-circle',
  chevron_back: 'chevron-back',
  chevron_down: 'chevron-down',
  chevron_foward: 'chevron-forward',
  chevron_up: 'chevron-up',
  checkmark: 'checkmark',
  american_football: 'american-football',
  time: 'time',
  tag: 'pricetag',
  navigate: 'navigate',
  chatbubble: 'chatbubble',
  pencil: 'pencil',
  person_add: 'person-add',
  checkmark_circle: 'checkmark-circle',
  checkmark_circle_outline: 'checkmark-circle-outline',
  swap_vertical: 'swap-vertical',
  eye: 'eye',
  eye_outline: 'eye-outline',
  eye_off: 'eye-off',
  eye_off_outline: 'eye-off-outline',
  print: 'print',
  print_outline: 'print-outline',
  trash: 'trash',
  trash_outline: 'trash-outline',
  images: 'images',
  images_outline: 'images-outline',
  scan: 'scan',
  camera_outline: 'camera-outline',
  happy_outline: 'happy-outline',
  bookmark: 'bookmark',
  pin: 'pin',
  gift: 'gift',
  bicycle: 'bicycle',
  airplane: 'airplane',
  barbell: 'barbell',
  book: 'book',
  build: 'build',
  cart: 'cart',
  cafe: 'cafe',
  game_controller: 'game-controller',
  school: 'school',
  information_circle_outline: 'information-circle-outline',
  list: 'list'
};
